# Create image based on the Skaffolder Node ES6 image
#FROM node:18.6.0 as builder
FROM node:18 as builder

WORKDIR /build

COPY package*.json /build/

RUN npm install

#RUN yarn global add @quasar/cli
#RUN npm install -g react-scripts@5.0.1
#RUN npm install -g md5
#RUN npm install -g prettier
#RUN npm install -g eslint  eslint-config  eslint-config-prettier eslint-plugin-prettier


RUN ls -a

COPY ./ /build/

#RUN node ./ng-add-pug-loader.js
RUN npx browserslist@latest --update-db

# Build prod
#RUN quasar build

RUN npm run build
RUN ls -a build

# ----------------------------------
# Prepare production environment
FROM nginx:alpine
# ----------------------------------

# Clean nginx
RUN rm -rf /usr/share/nginx/html/*

# Copy dist
COPY --from=builder /build/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
#COPY docker/99-url-replacement.sh /docker-entrypoint.d/99-url-replacement.sh

WORKDIR /usr/share/nginx/html

# Permission
RUN chown root /usr/share/nginx/html/*
RUN chmod 755 /usr/share/nginx/html/*


RUN ls -a /usr/share/nginx/html

# Expose port
EXPOSE 3000

# Start
CMD ["nginx", "-g", "daemon off;"]
