export const actionTypes = {
  GET_TASKS : "GET_TASKS",
  GET_TASKS_SUCCESS : "GET_TASKS_SUCCESS",
  GET_TASKS_FAILED: "GET_TASKS_FAILED",
  EDIT_TASK : "EDIT_TASK",
  EDIT_TASK_SUCCESS : "EDIT_TASK_SUCCESS",
  EDIT_TASK_FAILED: "EDIT_TASK_FAILED",
  EXPORT_DB : "EXPORT_DB",
  EXPORT_DB_SUCCESS : "EXPORT_DB_SUCCESS",
  EXPORT_DB_FAILED: "EXPORT_DB_FAILED",
  LOGIN_ADMIN_SUCCESS: "LOGIN_ADMIN_SUCCESS",
  LOGIN_ADMIN_FAILED: "LOGIN_ADMIN_FAILED",
  LOGOUT_ADMIN: "LOGOUT_ADMIN",
}